qr-code:
  namespace: qr-app
  image:
    registry: docker.io
    repository: shoun6000/qr-generator
    pullPolicy: IfNotPresent
    
  envConfig:
    DB_HOST: helm-charts-postgresql.qr-db.svc.cluster.local

postgresql:
  namespaceOverride: qr-db 
  image:
    registry: registry-1.docker.io
    repository: bitnamilegacy/postgresql
    tag: "latest"
    pullPolicy: IfNotPresent
  