apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.name }}-secret
  namespace: {{ .Values.app.namespace }}
  labels:
    app: {{ .Values.app.name }}
type: Opaque
data:
  POSTGRES_PASSWORD: {{ .Values.appSecret.POSTGRES_PASSWORD | b64enc | quote }}