app:
  name: qr-app
  namespace: qr-app
  replicaCount: 1
  
  image:
    repository: shoun6000/qr-generator
    tag: latest
    pullPolicy: IfNotPresent
  
  service:
    name: qr-app-loadbalancer
    type: LoadBalancer
    port: 8501
  
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"

configMap:
  POSTGRES_USER: admin
  POSTGRES_DB: qr_database
  DB_HOST: postgresql.qr-db.svc.cluster.local
  DB_PORT: "5432"

appSecret:
  POSTGRES_PASSWORD: admin


postgresql:
  #the dependency, by default enabled is true
  enabled: true
  nameOverride: postgresql
  namespaceOverride: qr-db
  
  image:
    repository: bitnamilegacy/postgresql
    tag: 15.15.0-debian-12-r1
    pullPolicy: IfNotPresent

  volumePermissions:
    enabled: true
    # image:
    #   repository: bitnamilegacy/os-shell
    #   tag: 12-debian-12-r51
    #   pullPolicy: Always

  # volumePermissions:
  # ## @param volumePermissions.enabled Enable init container that changes the owner and group of the persistent volume
  # ##
  # enabled: false
  # ## @param volumePermissions.image.registry [default: REGISTRY_NAME] Init container volume-permissions image registry
  # ## @param volumePermissions.image.repository [default: REPOSITORY_NAME/os-shell] Init container volume-permissions image repository
  # ## @skip volumePermissions.image.tag Init container volume-permissions image tag (immutable tags are recommended)
  # ## @param volumePermissions.image.digest Init container volume-permissions image digest in the way sha256:aa.... Please note this parameter, if set, will override the tag
  # ## @param volumePermissions.image.pullPolicy Init container volume-permissions image pull policy
  # ## @param volumePermissions.image.pullSecrets Init container volume-permissions image pull secrets
  # ##
  # image:
  #   registry: docker.io
  #   repository: bitnami/os-shell
  #   tag: 12-debian-12-r30
  #   digest: ""
  #   pullPolicy: IfNotPresent
  
  global:
    postgresql:
      auth:
        username: admin
        password: admin
        database: qr_database
  
  primary:
    persistence:
      enabled: true
      size: 1Gi
      storageClassName: standard
  
  service:
    type: ClusterIP
  
  postgresql:
    username: admin
    password: admin
    database: qr_database
    port: 5432
    dataDir: /var/lib/postgresql/data/pgdata
  
  volumePermissions:
    enabled: true  

  securityContext:
    enabled: true
    fsGroup: 999
    runAsUser: 999
  
  persistence:
    enabled: true
    mountPath: /var/lib/postgresql
    size: 1Gi
    accessModes: [ReadWriteOnce]





