apiVersion: v1
kind: ConfigMap
metadata:
  name: qr-app-config
  namespace: qr-app
data:
  POSTGRES_USER: admin
  POSTGRES_DB: qr_database
  DB_HOST: postgresql.qr-db.svc.cluster.local
  DB_PORT: "5432"