apiVersion: v1
kind: Service
metadata:
  name: qr-app-loadbalancer
  namespace: qr-app
  labels:
    app: qr-app-service
spec:
  type: LoadBalancer
  selector:
    app: qr-app-pod
  ports:
  - port: 8501
    targetPort: 8501
    protocol: TCP
    name: streamlit