apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app.name }}-config
  namespace: {{ .Values.app.namespace }}
data:
  POSTGRES_USER: {{ .Values.configMap.POSTGRES_USER | quote }}
  POSTGRES_DB: {{ .Values.configMap.POSTGRES_DB | quote }}
  DB_HOST: {{ .Values.configMap.DB_HOST | quote }}
  DB_PORT: {{ .Values.configMap.DB_PORT | quote }}