apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
  namespace: {{ .Values.postgres.namespace }}
spec:
  serviceName: {{ .Values.postgres.service.name }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.postgres.service.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.postgres.service.name }}
    spec:
      containers:
      - name: postgresql
        image: postgres:15
        ports:
        - containerPort: {{ .Values.postgres.service.port }}
          name: postgres
        
        env:
        - name: POSTGRES_USER
          value: {{ .Values.postgres.auth.username }}
        
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        
        - name: POSTGRES_DB
          value: {{ .Values.postgres.auth.database | quote}}
        
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        
        resources:
          requests:
            memory: {{ .Values.postgres.resources.requests.memory | quote}}
            cpu: {{ .Values.postgres.resources.requests.cpu | quote}}
          limits:
            memory: {{ .Values.postgres.resources.limits.memory | quote}}
            cpu: {{ .Values.postgres.resources.limits.cpu | quote}}
      
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc