apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.service.name}}
  namespace: {{ .Values.app.namespace }}
  labels:
    app: {{ .Values.app.name }}-service
spec:
  type: {{ .Values.app.service.type }}
  selector:
    app: {{ .Values.app.name }}-pod
  ports:
  - port: {{ .Values.app.service.port }}
    targetPort: {{ .Values.app.service.port }}
    protocol: TCP
    name: streamlit